Feature/admin2
thrashches/kristall_backend pull request #13
Opened 2023-12-21 11:24 UTC by FedXL

Чет я не понял куда комитить надо. Это администрирование. юзер модели.

2023-12-21 13:47 UTC, thrashches requested changes

2023-12-21 13:47 UTC, thrashches commented on backend/authorization/views.py
> +            return Response({"message": "User data updated"}, status=200)
Сообщения должны быть на русском. Сайт русскоязычный

2023-12-21 13:47 UTC, thrashches commented on backend/authorization/views.py
> +        return Response({"message": "User deleted"}, status=204)
Если ты отдаешь 204, то не надо отдавать body

2023-12-21 13:47 UTC, thrashches commented on backend/authorization/views.py
> +    def retrieve(self, request, *args, **kwargs):
ты должен писать свой метод `me` а не переопределять generic

2023-12-21 13:47 UTC, thrashches commented on backend/authorization/views.py
> +    def update(self, request, *args, **kwargs):
тоже самое

2023-12-21 13:47 UTC, thrashches commented on backend/authorization/views.py
> +    def destroy(self, request, *args, **kwargs):
и это

2023-12-21 13:47 UTC, thrashches commented on backend/authorization/views.py
> +class ChangePasswordView(APIView):
все это можно было засунуть во вьюсет

2023-12-21 13:47 UTC, thrashches commented on backend/backend/secret.py
> +GOOGLE_SECRET = {"web":
этого не должно тут быть

2023-12-21 13:47 UTC, thrashches commented on backend/backend_api/urls.py
> +router_goods.register(r'user/me', ChangeUserDataViewSet, basename='users_viewset')
регистрируй `users`, `/me/` - это должен быть метод во вьюсете

2023-12-24 10:05 UTC, thrashches requested changes

2023-12-24 10:05 UTC, thrashches commented on backend/authorization/views.py
> +        username = self.request.user.username
Ты получаешь из объекта пользователя `username`, а потом по `username` получаешь пользователя? Может быть сразу брать пользователя?

2023-12-24 10:05 UTC, thrashches commented on backend/authorization/views.py
> +        serialized_user = self.serializer_class(user)
правильнее использовать соответствующие методы, а не свойства:
`self.serializer_class` -> `self.get_serializer_class( <сюда бы еще контекст передать> )`

2023-12-24 10:05 UTC, thrashches commented on backend/authorization/views.py
> +        serializer = self.serializer_class(user, data=data)
аналогично

2023-12-24 10:05 UTC, thrashches commented on backend/authorization/views.py
> +        user = request.user
путсть точкой правды будет `get_object`

2023-12-24 10:05 UTC, thrashches commented on backend/authorization/views.py
> +class ChangeUserDataViewSet2(viewsets.ViewSet):
Старый лучше закомментировать, чем называть переменные цифрами

2023-12-24 10:05 UTC, thrashches commented on backend/authorization/views.py
> +        serializer = self.serializer_class(data=request.data, context={'request': request})
`get_serializer_class`. А вообще можно определить метод `get_serializer` и в нем все это разруливать.

2023-12-24 10:05 UTC, thrashches commented on backend/authorization/views.py
> +        return Response({"message": f"Хотя бы одно поле должно быть заполнено."}, status=status.HTTP_400_BAD_REQUEST)
Здесь лучше дернуть реальные ошибки проверки сериализатора и отдать их в ответе.

2023-12-24 10:05 UTC, thrashches commented on backend/backend/urls.py
> +    path('api/v1/', include(router_goods.urls)),
Должно быть `path('api/v1/', include('backend_api.urls'))` и все. Одна строчка.

2023-12-24 10:05 UTC, thrashches commented on backend/backend_api/urls.py
>  router_goods = SimpleRouter()
Пусть будет общий роутер на все эндпоинты. Не надо городить отдельный роутер под каждое приложение

2023-12-24 10:15 UTC, FedXL commented on backend/authorization/views.py
> +        serializer = self.serializer_class(data=request.data, context={'request': request})
давай уже не откланяться . По сериализаторам у нас будет отдельная серия)

2023-12-24 10:23 UTC, FedXL commented on backend/authorization/views.py
> +        username = self.request.user.username
Вот я я так сделал. А ты сказал читай про request.user я прочитал. И в итоге есть варианты когда таким методом не user = self.request.user Не всегда можно получить объект с полными полями. 
![Uploading 1.png…]()
Я подумал что так универсальнее.

2023-12-24 10:25 UTC, FedXL commented on backend/authorization/views.py
> +        username = self.request.user.username
Я ещё удивился. Ну придумали что в реквест. Юзера при авторизации добавляют. Почему нет доступа ко всем полям.

2023-12-24 11:50 UTC, FedXL commented on backend/authorization/views.py
> +        serialized_user = self.serializer_class(user)
почему?

2023-12-25 10:27 UTC, thrashches requested changes
Либо оставь этот вьюсет уже мне, не мучайся, либо подключай его корректно. Он подключается одной строкой.

2023-12-25 10:27 UTC, thrashches commented on backend/authorization/views.py
> +        return Response({"messages": f"Неправильные данные {serializer.errors}"}, status=status.HTTP_400_BAD_REQUEST)
Зачем `json` засовывать в строку? Как это потом парсить? Отдай сами ошибки и все.

2023-12-25 10:27 UTC, thrashches commented on backend/authorization/views.py
> +                    'first_name': openapi.Schema(type=openapi.TYPE_STRING, description='User\'s first name'),
Сайт русскоязычный. Давай доки тоже по-русски писать.

2023-12-25 10:27 UTC, thrashches commented on backend/authorization/views.py
> +    authentication_classes = [TokenAuthentication]
`permission_class` достаточно, класс авторизации фреймворк тянет сам

2023-12-25 10:27 UTC, thrashches commented on backend/authorization/views.py
> +        return Response({"message": f"Неправильные данные: {serializer.errors}"},
аналогично

2023-12-25 10:27 UTC, thrashches commented on backend/backend/urls.py
> -from django.contrib import admin
Зачем ломать админку?

2023-12-25 10:27 UTC, thrashches commented on backend/backend_api/urls.py
> +    path('admin/', admin.site.urls),
Зачем?

2023-12-25 10:27 UTC, thrashches commented on backend/backend_api/urls.py
> +    path('users/', ChangeUserDataViewSet.as_view({
нет

2023-12-25 10:27 UTC, thrashches commented on backend/backend_api/urls.py
> +    path('users/me/', ChangeUserDataViewSet.as_view({'put': 'me'}), name='user-change-password'),
нет

2023-12-25 10:27 UTC, thrashches commented on backend/backend_api/urls.py
> +    path('users/', ChangeUserDataViewSet.as_view({
Юзай роутер, в чем проблема то?

2023-12-25 13:47 UTC, FedXL commented on backend/backend_api/urls.py
> +    path('admin/', admin.site.urls),
НУ ты сказал что должно быть v1/api/ одно строчка я подумал что и админку туда.

2023-12-26 09:30 UTC, thrashches commented
Все поменял. Сливаю

2023-12-26 09:31 UTC, merged