Feature/authorization
thrashches/kristall_backend pull request #6
Opened 2023-12-15 21:22 UTC by FedXL

Ну ладно фиг с ним с рефреш токеном а просрочится перенаправляй на страничку авторизации

2023-12-16 07:29 UTC, thrashches commented on backend/authorization/auth_class.py
> +class JWTTokenFromCookieUserAuthentication(JWTTokenUserAuthentication):
[Что лучше юзать в нашем случае](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)

2023-12-16 08:11 UTC, thrashches requested changes
В общем основное - переходим на простые токены. Вьюхи для API мы используем `APIView`, их наследников или `ViewSet`. Файлы миграций положи в репозиторий. Экспериментальные модели лучше убрать. Если тебе для проверки нужны давай я сделаю несколько штук, которые нужны будут.

2023-12-16 08:11 UTC, thrashches commented on .gitignore
> +**/migrations/
Никогда так не делай, мы потом ошибок наловим при развертывании базы. Миграции должны быть в репозитории

2023-12-16 08:11 UTC, thrashches commented on backend/authorization/models.py
> +        ('phone', 'Phone'),
Используй русские названия `('phone', 'Через телефон')`

2023-12-16 08:11 UTC, thrashches commented on backend/authorization/models.py
> +        verbose_name = 'Crystal User'
Аналогично

2023-12-16 08:11 UTC, thrashches commented on backend/authorization/views.py
> +class OAuthCookieGoogleInjection(View):
Используй класс `APIView` для эндпоинтов API

2023-12-16 08:11 UTC, thrashches commented on backend/authorization/views.py
> +                    return HttpResponse(f'Fail in getting user info from google {er}')
Тут можно использовать `Response` и отдавать JSON. Нам это на фронте обрабатывать. [Дока](https://www.django-rest-framework.org/api-guide/responses/#response)

2023-12-16 08:11 UTC, thrashches commented on backend/authorization/views.py
> +                response = HttpResponse(f"SUCCESS, I want to redirect from here {result}. Check cookie. We have access "
И тут

2023-12-16 08:11 UTC, thrashches commented on backend/authorization/views.py
> +                return HttpResponse(f"We dont have a google access token. Why? 400 token response")
И тут

2023-12-16 08:11 UTC, thrashches commented on backend/authorization/views.py
> +        return Response(result)
Вот как здесь

2023-12-16 08:11 UTC, thrashches commented on backend/backend/settings.py
>  LANGUAGE_CODE = 'en-us'
Поменяй на `ru-ru`, а `TIME_ZONE` на `Europe/Moscow`

2023-12-16 08:11 UTC, thrashches commented on backend/backend_api/models.py
> +class MyModel(models.Model):
???

2023-12-16 08:11 UTC, thrashches commented on backend/backend_api/views.py
> +    authentication_classes = [JWTTokenFromCookieUserAuthentication]
Мы класс авторизации устанавливаем в настройках, а в `APIView` указываем `permission_classes`. Их тоже можно задать в секции `REST_FRAMEWORK` в `settings.py`.

2023-12-16 08:11 UTC, thrashches commented on backend/backend/settings.py
> +        'rest_framework_simplejwt.authentication.JWTAuthentication',
Меняем y на `authtoken`. В заголовках будет следующее: `Authorization: Token <токен пользователя>`.

2023-12-16 08:11 UTC, thrashches commented on backend/backend/settings.py
> +        'ENGINE': 'django.db.backends.postgresql',
Огонь! Я запилю конфиг для докера, смержишь себе потом.

2023-12-18 08:18 UTC, thrashches requested changes

2023-12-18 08:18 UTC, thrashches commented on backend/authorization/serializers.py
> +class AuthByPhone(serializers.Serializer):
Называй сериализаторы по шаблону `ДляЧегоSerializer`

2023-12-18 08:18 UTC, thrashches commented on backend/authorization/serializers.py
> +class AuthPswSerializer(serializers.Serializer):
Лучше пусть будет Password вместо Psw)

2023-12-18 08:18 UTC, thrashches commented on backend/authorization/urls.py
> +    path('email/', ObtainTokenByPsw.as_view(), name='get token by psw and email'),
name должен быть без пробелов, юзай `snake_case`, либо не юзай name для api

2023-12-18 08:18 UTC, thrashches commented on backend/authorization/views.py
> +def vkOauthTest(request):
[pep8](https://peps.python.org/pep-0008/#function-and-variable-names)

2023-12-18 08:18 UTC, thrashches commented on backend/authorization/views.py
> +def googleOauthTest(request):
[pep8](https://peps.python.org/pep-0008/#function-and-variable-names)

2023-12-18 08:18 UTC, thrashches commented on backend/authorization/views.py
> +            psw = serializer.validated_data['password']
просто чтобы потом было легче дебажить `password`

2023-12-18 08:18 UTC, thrashches commented on backend/authorization/views.py
> +        responses={
Четко. Так же делаю

2023-12-18 08:18 UTC, thrashches commented on backend/authorization/utils.py
> +from backend.settings import GOOGLE_OAUTH, VK_OAUTH
Так нельзя импортировать настройки. Юзай так:
```python
from django.conf import settings

data = settings.GOOGLE_OAUTH.get('web')
```

2023-12-18 08:18 UTC, thrashches commented on backend/backend/loggers.py
> +project_directory = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
можно юзать `settings.BASE_DIR`

2023-12-18 08:18 UTC, thrashches commented on backend/backend_api/migrations/0001_initial.py
> +# Generated by Django 5.0 on 2023-12-17 19:43
этот мусор лучше спрятать

2023-12-18 09:39 UTC, FedXL commented on backend/authorization/utils.py
> +from backend.settings import GOOGLE_OAUTH, VK_OAUTH
Вот тут не понял. Почему?

2023-12-18 10:50 UTC, thrashches approved these changes
Попозже добавлю конфиг для докера, переменные переместим в secrets

2023-12-18 10:50 UTC, merged